name: Zvision
favicon: null
layout_spectrum: 0.7598354246001691
typography_spectrum: 0.7449281341396272
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.0954249557107687
  lightness: 0.5050916052423418
  saturation: 0.6398707674816251
  rhythmicContrast: 0.8519065915606916
purpose: []
